set nocompatible						" use vim settings, rather then vi settings
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
" let g:solarized_termcolors=256
syntax enable

set nobackup
set nowritebackup
set noswapfile

set numberwidth=4
set relativenumber

set wildmenu

set laststatus=2						" always display the status line
set showmatch
set ignorecase smartcase
set hlsearch
set incsearch							" do incremental searching
"set smartindent
"set smarttab
"set autoindent							" always set autoindenting on
"set tabstop=4
"set softtabstop=4
"set shiftwidth=4
set encoding=utf-8
set autoread
set history=50							" keep 50 lines of command line history
set showcmd								" display incomplete commands


map <C-n> :NERDTreeToggle<CR>	" shortcut to open nerdtree
" close vim when only window left open is nerdtree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

filetype plugin on		" required for nerd commenter plugin
