" use vim settings rather than vi settings
set nocompatible

" use pathogen for managing vim modules
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

" allow syntax highlighting
syntax enable

" disable generation of backup and swap files
set nobackup
set nowritebackup
set noswapfile

" set width of line numbering to four characters
set numberwidth=4

" set line numbers relative to currunt line
set relativenumber
set number

" enable command auto completion
set wildmenu
set wildmode=list:longest,full

" always display the status line
set laststatus=2

" enable smart-case-sensitivity searching
set ignorecase
set smartcase

" highlight all search results
set hlsearch

" show the next match while entering a search query
set incsearch

" set default encoding to utf-8
set encoding=utf-8

" read file again if modified by another editor
set autoread

" keep 50 lines of command line history
set history=50

" display incomplete commands
set showcmd

" support expected backspace functionality in insert mode
set backspace=indent,eol,start

" show 80 char line
set colorcolumn=80

" ctrl-n should toggle nerd-tree pane
map <C-n> :NERDTreeToggle<CR>   " shortcut to open nerdtree

" close vim when only window left open is nerdtree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" required for nerd commenter plugin
filetype plugin on

" make quit command case-insensitive
:command Q q

" make save command case-insensitive
:command W w

" make save and exit command case-insensitive
:command Wq wq

" by default, set tabstop to two chars
set tabstop=2

" by default, use spaces instead of tabs
set expandtab

" only on ubuntu
" enable this on ubuntu, disable for osx
" colorscheme evening

" only on ubuntu
" set vim-airline module theme
" let g:airline_theme='papercolor'

let g:typescript_indent_disable=1
