#!/usr/bin/env bash

CLICOLOR=1
PS1="\u@\h:\w$ "
TERM="xterm-color"
export LANG="en_US.UTF-8"
export GPG_TTY=$(tty)

if hash "brew" 2>/dev/null; then
    if [ -f "$(brew --prefix)/etc/bash_completion" ]; then
        . $(brew --prefix)/etc/bash_completion
    fi
fi

alias ls="ls -G"
alias dc="docker-compose"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
