#!/bin/bash

CLICOLOR=1
PS1="\u@\h:\w$ "
TERM="xterm-color"
export LANG="en_US.UTF-8"
export GPG_TTY=$(tty)

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

alias ls="ls -G"
alias dc="docker-compose"

eval "$(rbenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/pejman/google-cloud-sdk/path.bash.inc' ]; then
  source '/Users/pejman/google-cloud-sdk/path.bash.inc';
fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/pejman/google-cloud-sdk/completion.bash.inc' ];
  then source '/Users/pejman/google-cloud-sdk/completion.bash.inc';
fi
