#!/usr/bin/env bash

export CLICOLOR=1
export PS1="\u@\h:\w$ "
export TERM="screen-256color"
export LANG="en_US.UTF-8"
export GPG_TTY=$(tty)
export EDITOR="$(which vim)"

alias ls="ls -G"
alias grep="grep --color"
alias dc="docker-compose"
alias vi="vim"

if hash "brew" 2>/dev/null; then
    if [ -f "$(brew --prefix)/etc/bash_completion" ]; then
        . $(brew --prefix)/etc/bash_completion
    fi
fi

export PATH="$PATH:/usr/local/sbin"
export PATH="$PATH:/usr/local/sbin"
export PATH="$PATH:/usr/local/opt/python/libexec/bin"
export PATH="$PATH:$HOME/.cargo/bin"
